{{- range .Values.microservices}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-{{ .name }}
spec:
  selector:
    matchLabels:
      app: code-{{ .name }}
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels:
        app: code-{{ .name }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image}}
          imagePullPolicy: {{ $.Values.pullPolicy }}
          {{- with .command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /configs
              name: config-volume
          ports:
            {{- range .service }}
            - containerPort: {{.}}
            {{- end }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: code-config
---
{{- end}}