apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-backend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: code.vinf.top
      http:
        paths:
          - path: /api/batch
            pathType: Prefix
            backend:
              service:
                name: code-dispatcher
                port:
                  number: 8080
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: code-user
                port:
                  number: 8080
          - path: /api/result
            pathType: Prefix
            backend:
              service:
                name: code-result
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-nginx
                port:
                  number: 80

