apiVersion: v1
kind: Service
metadata:
  name: code-nginx
  labels:
    app: code-nginx
spec:
  ports:
    - port: 80
      name: code-web
  selector:
    app: code-nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: code-web
spec:
  serviceName: "code-nginx"
  replicas: 1
  selector:
    matchLabels:
      app: code-nginx
  template:
    metadata:
      labels:
        app: code-nginx
    spec:
      containers:
        - name: code-nginx
          image: docker.io/library/nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

