# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pullPolicy: Always

microservices:
  - name: dispatcher
    replicaCount: 1
    image: registry.cn-shanghai.aliyuncs.com/codev/dispatcher:latest
    command:
      - dispatcher-svc
      - --port=8080
      - --config-path=/configs/config.yaml
    service:
      - 8080

  - name: user
    replicaCount: 1
    image: registry.cn-shanghai.aliyuncs.com/codev/user:latest
    command:
      - user-svc
      - --port=8080
      - --config-path=/configs/config.yaml
    service:
      - 8080

  - name: result
    replicaCount: 1
    image: registry.cn-shanghai.aliyuncs.com/codev/result:latest
    command:
      - result-svc
      - --port=8080
      - --config-path=/configs/config.yaml
    service:
      - 8080

  - name: python-actuator
    replicaCount: 2
    image: registry.cn-shanghai.aliyuncs.com/codev/python-actuator:latest
    command:
      - actuator
      - --port=8080
      - --config-path=/configs/config.yaml
    service:
      - 8080

  - name: js-actuator
    replicaCount: 2
    image: registry.cn-shanghai.aliyuncs.com/codev/js-actuator:latest
    command:
      - actuator
      - --port=8080
      - --config-path=/configs/config.yaml
    service:
      - 8080

imagePullSecrets: []

